name: CI + CD

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo "Hello, world!"

  DeployDev:
    name: Deploy to Development
    if: github.ref_name == 'develop'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo "Deploying to Development..."

  DeployQA:
    name: Deploy to QA
    if: github.ref_name == 'develop'
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment:
      name: QA
      url: 'http://qa.myapp.com'
    steps:
      - name: Deploy
        run: echo "Deploying to QA..."

  DeployStaging:
    name: Deploy to Staging
    if: github.ref_name == 'develop'
    needs: [DeployQA]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://staging.myapp.com'
    steps:
      - name: Deploy
        run: echo "Deploying to Staging..."

  DeployProd:
    name: Deploy to Production
    if: github.ref_name == 'main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo "Deploying to Production..."
