name: CI + CD + Deploy

on:
  push:
    branches:
      - Development
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
jobs:
  # ========== BUILD + DEPLOY DEV ==========
  BuildDev:
    if: github.ref_name == 'Development'
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image (Dev)
        run: |

          docker build \
            -t $ECR_REPOSITORY:latest .

  DeployDev:
    needs: BuildDev
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - run: echo "Deploying Dev environment..."

  # ========== BUILD + DEPLOY QA ==========
  BuildQA:
    if: github.ref_name == 'Development'
    needs: DeployDev
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image (QA)
        run: |
          IMAGE_TAG=qa-${{ github.sha }}
          docker build \
            -t $ECR_REPOSITORY:latest .


  DeployQA:
    needs: BuildQA
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - run: echo "Deploying QA environment..."

  # ========== BUILD + DEPLOY STAGING ==========
  BuildStaging:
    if: github.ref_name == 'Development'
    needs: DeployQA
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image (Staging)
        run: |
          IMAGE_TAG=staging-${{ github.sha }}
          docker build \
            -t $ECR_REPOSITORY:latest .


  DeployStaging:
    needs: BuildStaging
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - run: echo "Deploying Staging environment..."

  # ========== BUILD + DEPLOY PRODUCTION ==========
  BuildProd:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image (Prod)
        run: |
          IMAGE_TAG=prod-${{ github.sha }}
          docker build \
            -t $ECR_REPOSITORY:latest .

  DeployProd:
    needs: BuildProd
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - run: echo "Deploying Production environment..."
